mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views
from . import models
from ads.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name = 'all'),
    # path('ad/<int:pk>',
    #     OwnerDetailView.as_view(
    #         model = models.Ad,
    #         template_name = app_name+"/ad_detail.html"),
    #     name='ad_detail'),

    # path('ad/create',
    #     OwnerCreateView.as_view(
    #         success_url=reverse_lazy(app_name+':all'),
    #         model = models.Ad,
    #         template_name = app_name+"/ad_form.html",
    #         fields = ['title', 'text']
    #      ), name='ad_create'),

    # path('ad/<int:pk>/update',
    #     OwnerUpdateView.as_view(
    #         success_url=reverse_lazy(app_name+':all'),
    #         model = models.Ad,
    #         fields = ['title', 'text'],
    #         template_name = app_name+"/ad_form.html"
    #     ), name='ad_update'),

    # path('ad/<int:pk>/delete',
    #     OwnerDeleteView.as_view(
    #         success_url=reverse_lazy(app_name+':all'),
    #         model = models.Ad,
    #         template_name = app_name+"/ad_confirm_delete.html"
    #     ), name='ad_delete'),

    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),

    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    path('ads/', include('ads.urls')),


]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/pets/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'pets'
urlpatterns = [
    path('', views.PetList.as_view(), name='all'),
    path('main/create/', views.PetCreate.as_view(), name='pet_create'),
    path('main/<int:pk>/update/', views.PetUpdate.as_view(), name='pet_update'),
    path('main/<int:pk>/delete/', views.PetDelete.as_view(), name='pet_delete'),
    path('lookup/', views.TypeList.as_view(), name='type_list'),
    path('lookup/create/', views.TypeCreate.as_view(), name='type_create'),
    path('lookup/<int:pk>/update/', views.TypeUpdate.as_view(), name='type_update'),
    path('lookup/<int:pk>/delete/', views.TypeDelete.as_view(), name='type_delete'),
]

mysite/pets/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Type(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Type must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Pet(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    age = models.PositiveIntegerField()
    cost = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    type = models.ForeignKey('Type', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/pets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from pets.models import Pet, Type


# Create your views here.


class PetList(LoginRequiredMixin, View):
    def get(self, request):
        mc = Type.objects.all().count()
        al = Pet.objects.all()

        ctx = {'type_count': mc, 'pet_list': al}
        return render(request, 'pets/pet_list.html', ctx)


class TypeList(LoginRequiredMixin, View):
    def get(self, request):
        ml = Type.objects.all()
        ctx = {'type_list': ml}
        return render(request, 'pets/type_list.html', ctx)


# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class TypeCreate(LoginRequiredMixin, CreateView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class TypeUpdate(LoginRequiredMixin, UpdateView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


class TypeDelete(LoginRequiredMixin, DeleteView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('pets:all')



# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class PetCreate(LoginRequiredMixin, CreateView):
    model = Pet
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


class PetUpdate(LoginRequiredMixin, UpdateView):
    model = Pet
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


class PetDelete(LoginRequiredMixin, DeleteView):
    model = Pet
    fields = '__all__'
    success_url = reverse_lazy('pets:all')

# We use reverse_lazy rather than reverse in the class attributes
# because views.py is loaded by urls.py and in urls.py as_view() causes
# the constructor for the view class to run before urls.py has been
# completely loaded and urlpatterns has been processed.

# References

# https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#createview

mysite/pets/templates/pets/pet_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Pet</h1>

<p>Are you sure you want to delete the pet: {{ pet }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/pets/templates/pets/pet_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'pets:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/pets/templates/pets/pet_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Pets List</h1>
  {% if pet_list %}
  <ul>
    {% for pet in pet_list %}
      <li>
          {{ pet.nickname }} ({{ pet.type }})
          (<a href="{% url 'pets:pet_update' pet.id %}">Update</a> |
          <a href="{% url 'pets:pet_delete' pet.id %}">Delete</a>) <br/>

      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no pets in the library.</p>
  {% endif %}
  <p>
    {% if type_count > 0 %}
      <a href="{% url 'pets:pet_create' %}">Add a pet</a>
    {% else %}
      Please add a type before you add an pet.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'pets:type_list' %}">View types</a> ({{ type_count }}) |
    <a href="{% url 'pets:type_create' %}">Add a type</a>
  </p>
{% endblock %}

mysite/pets/templates/pets/type_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Type</h1>

<p>Are you sure you want to delete the type: {{ type }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'pets:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/pets/templates/pets/type_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'pets:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/pets/templates/pets/type_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Types List</h1>
  {% if type_list %}
  <ul>
    {% for type in type_list %}
      <li>
          {{ type.name }}
         (<a href="{% url 'pets:type_update' type.id %}">Update</a> |
          <a href="{% url 'pets:type_delete' type.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no types in the library.</p>
  {% endif %}
  <p><a href="{% url 'pets:type_create' %}">Add a type</a></p>
  <p>
    <a href="{% url 'pets:all' %}">Back to pets</a>
  </p>
{% endblock %}